name: pru-db
on:
  push:
    branches:
      - main
    paths:
      - "db/*"
permissions:
  contents: write
  pull-requests: write
jobs:
  pru:
    name: pru
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with GitHub App
        id: gh-app-auth
        uses: kanmu/gh-app-auth@main
        with:
          app-id: 281788
          private-key: ${{ secrets.GH_APP_AUTH_PRIVATE_KEY }}
          account: winebarrel
      - uses: winebarrel/pru-action@v0.3.0
        with:
          paths: db/*
          github-token: ${{ steps.gh-app-auth.outputs.token }}
