name: pru-db
on:
  push:
    branches:
      - main
    paths:
      - "db/*"
permissions:
  contents: write
  pull-requests: write
jobs:
  pru:
    name: pru
    runs-on: ubuntu-latest
    steps:
      - uses: winebarrel/pru-action@v0.3.0
        with:
          paths: db/*
          github-token: ${{ secrets.PAT }}
