name: pru-lb
on:
  push:
    branches:
      - main
    paths:
      - "lb/*"
permissions:
  contents: write
  pull-requests: write
jobs:
  pru:
    name: pru
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: winebarrel/pru-action@v0.3.0
        with:
          paths: lb/*
