name: "Terraform DB"
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/terraform.yml
      - .github/workflows/terraform-db.yml
      - "db/*"
  pull_request:
    paths:
      - .github/workflows/terraform.yml
      - .github/workflows/terraform-db.yml
      - "db/*"

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    uses: winebarrel/terraform-with-github-actions/.github/workflows/terraform.yml@main
    with:
      name: db
      sha: ${{ github.event_name == 'push' && github.sha || github.event.pull_request.head.sha }}
    secrets:
      access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
